name = "SHAKE"
uuid = "9c8de619-9405-45f5-abce-b523323dfc2f"
authors = ["Erich Neun <erich-9@gmx.de> and contributors"]
version = "0.0.1"

[deps]
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
Aqua = "0.8"
SHA = "<0.0.1, 0.7, 1"
Test = "<0.0.1, 1"
julia = "1.1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
